PROG=test_ftnunit

SRCS =	ftnunit.f90 test_ftnunit.f90

OBJS =	ftnunit.o test_ftnunit.o

#Example to include specific netcdf libraries: 
#LIBS = -lm -lfftw3 -lfftw3f -L $(HOME)/local/lib -lnetcdff -Wl,-rpath,$(HOME)/local/lib 

LIBS =  

# set unc to compile with netcdf: 
#F90FLAGS = -Dunc 
CC = gcc
CFLAGS = -O3 -DF_UNDERSCORE
F90 = mpif90 -O3  -fbacktrace 
FC = gfortran -O3 -fbacktrace 
INCLUDE = -I /usr/include 
# to include local built of netcdf you might want to use sth like this: 
#INCLUDE = -I $(HOME)/local/include -I /usr/include 


# cancel m2c implicit rule 
%.o : %.mod 
 

all: $(PROG)

$(PROG): $(OBJS)
	$(F90) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(PROG) $(OBJS) *.M *.mod *.d *.il core 

.SUFFIXES: $(SUFFIXES) .f90 .F90

.f90.o:
	$(F90) $(F90FLAGS) -c $(INCLUDE) $<

.F90.o:
	$(F90) $(F90FLAGS) -c $(INCLUDE) $<

ftnunit.o:  Makefile 
test_ftnunit.o: ftnunit.o Makefile 
